### ISSUE TITLE
Can't find gruntfile when using different base dir

### ISSUE THREAD

**Issue by RefuX** [srs/gradle-grunt-plugin#11]
12:32:36.652 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'node''. Working directory: /Users/me/Development/project/LCTWeb Command: node /Users/me/Development/project/LCTWeb/node_modules/grunt-cli/bin/grunt --base ../LctWebApp/ --gruntfile ../LctWebApp/Gruntfile.js test
12:32:38.792 [QUIET] [system.out] Fatal error: Unable to find Gruntfile.

But from terminal (from  /Users/me/Development/project/LCTWeb) this works:
grunt --base ../LctWebApp/ --gruntfile ../LctWebApp/Gruntfile.js test

**Comment by srs** [comment]
Closing this since it is probably not an issue anymore.
