### ISSUE TITLE
Change js project root and output directory 

### ISSUE THREAD

**Issue by bgaborg** [srs/gradle-grunt-plugin#13]
I'm using gradle-grunt-plugin to run Grunt build in a project.
The Grunt build file is in ./src/main/webapp/js (where ./ is the project root), but the gradle plugin runs grunt from ./, so the build file can not be found.

Although it's possible to give command line parameters to grunt, I haven't found any solution to set ./src/main/webapp/js/ for running the grunt build.

Is it possible to set the grunt file location by command line parameter? (and also the grunt project root, because all js files are located relative to that path)

**Comment by srs** [comment]
Closing this one.
