### ISSUE TITLE
Plugin v0.6 with Java 1.6

### ISSUE THREAD

**Issue by bmehta** [srs/gradle-grunt-plugin#20]
Hi,
I am using Java 1.6 (mandated by the client). Trying to use this extremely helpful plugin to run grunt tasks, but keep running into the error below. I suspect it is because the plugin is built with a later version of Java. Any chance you could help me resolve this? Thanks.

com/moowork/gradle/node/NodePlugin : Unsupported major.minor version 51.0

**Comment by bmehta** [comment]
Tried to compile the source using 
"gradlew clean build", but run into this error:

> com/moowork/gradle/node/task/NpmTask : Unsupported major.minor version 51.0

**Comment by srs** [comment]
Changed the compile compatibility to 1.6. Should work now.
