### ISSUE TITLE
Grunt tasks fail in Gradle multi project architecture

### ISSUE THREAD

**Issue by mhmxs** [srs/gradle-grunt-plugin#31]
Hi there,
First of all i like your stuff, and works perfect on a single Gradle project, but i have a multi project system, and it fails.

It sets `localGrunt` and 'workingDir" as well, so the location by default is the sub project's location. But it executes the grunt command from the project root, so the `Gruntfile.js` will never found.

My suggestion is to specify `Gruntfile.js` location. Here is my [change](https://github.com/mhmxs/gradle-grunt-plugin/commit/7a6637fc8628195d80359708a09c656fe17c72e6) it works on single and multi projects too, because the file location is the project work dir. If you are happy with it i would send the PR. 

Thanks

**Comment by jean-morissette** [comment]
We also encounter the same problem in our multi Gradle project. What is the situation on that issue? Can you fix it soon?

**Comment by mhmxs** [comment]
We have a fixed [version](https://github.com/sequenceiq/cloudbreak/blob/master/web/build.gradle#L9) in our maven repository.
